# Generated by Django 2.2.15 on 2021-03-12 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilesAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
                ('adminupload', models.FileField(upload_to='media')),
            ],
        ),
    ]
