# Generated by Django 2.2.15 on 2021-03-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ciber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_number', models.CharField(max_length=50)),
                ('amount_elements', models.FloatField()),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
