# Generated by Django 2.2.15 on 2021-03-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_ciber', '0002_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='credit',
            new_name='price',
        ),
    ]
