# Generated by Django 2.2.15 on 2021-03-15 00:15

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_ciber', '0003_auto_20210312_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesadmin',
            name='res',
            field=jsonfield.fields.JSONField(default='{}'),
        ),
    ]
